version: "3.5"
services:
  mev-boost:
    build:
      context: src
      args:
        UPSTREAM_VERSION: v1.3.0
    volumes:
      - "data:/var/lib/mev-boost"
    environment:
      RELAYS: >-
        https://0x8b5d2e73e2a3a55c6c87b8b6eb92e0149a125c852751db1422fa951e42a09b82c142c3ea98d0d9930b056a3bc9896b8f@bloxroute.max-profit.blxrbdn.com,https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net
      EXTRA_OPTS: ""
    image: "mev-boost.mev-boost.dnp.dappnode.eth:0.1.2"
    restart: unless-stopped
volumes:
  data: {}
